# Assignment_5 : Multiple_Linear_Regression_TC

Consider only the below columns and prepare a prediction model for predicting Price.

Corolla<-Corolla[c("Price","Age_08_04","KM","HP","cc","Doors","Gears","Quarterly_Tax","Weight")]


In [8]:
import pandas as pd
import seaborn as sns
import statsmodels.formula.api as smf

In [9]:
df = pd.read_csv('C:/Users/malho/Downloads/ToyotaCorolla.csv', encoding="ISO-8859-1")
df.head()

Id                                           Model  Price  Age_08_04  \
0   1   TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13500         23   
1   2   TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13750         23   
2   3   TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13950         24   
3   4   TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  14950         26   
4   5     TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors  13750         30   

   Mfg_Month  Mfg_Year     KM Fuel_Type  HP  Met_Color  ... Central_Lock  \
0         10      2002  46986    Diesel  90          1  ...            1   
1         10      2002  72937    Diesel  90          1  ...            1   
2          9      2002  41711    Diesel  90          1  ...            0   
3          7      2002  48000    Diesel  90          0  ...            0   
4          3      2002  38500    Diesel  90          0  ...            1   

   Powered_Windows  Power_Steering  Radio  Mistlamps  Sport_Model  \
0                1               1      0          0            0   
1                0               1      0          0            0   
2                0               1      0          0            0   
3                0               1      0          0            0   
4                1               1      0          1            0   

   Backseat_Divider  Metallic_Rim  Radio_cassette  Tow_Bar  
0                 1             0               0        0  
1                 1             0               0        0  
2                 1             0               0        0  
3                 1             0               0        0  
4                 1             0               0        0  

[5 rows x 38 columns]

# EDA

In [10]:
df.isna().sum()

Id                  0
Model               0
Price               0
Age_08_04           0
Mfg_Month           0
Mfg_Year            0
KM                  0
Fuel_Type           0
HP                  0
Met_Color           0
Color               0
Automatic           0
cc                  0
Doors               0
Cylinders           0
Gears               0
Quarterly_Tax       0
Weight              0
Mfr_Guarantee       0
BOVAG_Guarantee     0
Guarantee_Period    0
ABS                 0
Airbag_1            0
Airbag_2            0
Airco               0
Automatic_airco     0
Boardcomputer       0
CD_Player           0
Central_Lock        0
Powered_Windows     0
Power_Steering      0
Radio               0
Mistlamps           0
Sport_Model         0
Backseat_Divider    0
Metallic_Rim        0
Radio_cassette      0
Tow_Bar             0
dtype: int64

In [11]:
print(df.Doors.unique())
print(df.Gears.unique())
print(df.HP.unique())
print(df.cc.unique())
print(df.Quarterly_Tax.unique())
print(df.Weight.unique())
print(df.Age_08_04.unique())

[3 5 4 2]
[5 6 3 4]
[ 90 192  69 110  97  71 116  98  86  72 107  73]
[ 2000  1800  1900  1600  1400  1598 16000  1995  1398  1300  1587  1975
  1332]
[210 100 185  85  19 234  69 283  64 197 163  72  40]
[1165 1170 1245 1185 1105 1065 1120 1100 1255 1270 1110 1195 1180 1075
 1130 1275 1060 1115 1265 1260 1125 1155 1045 1480 1320 1280 1135 1090
 1150 1085 1160 1205 1084 1140 1095 1025 1119 1080 1121 1615 1067 1040
 1030 1055 1050 1103 1070 1035 1015 1000 1078 1079 1109 1020 1010 1114
 1172 1094 1083]
[23 24 26 30 32 27 25 22 31 28 29 20 19 16 17 11 18 13 14  4  8  7 15 10
 12  9  6  2  1 43 38 40 44 41 37 39 42 35 34 33 36 53 51 54 45 55 48 52
 49 56 50 47 46 58 68 59 62 65 67 64 60 61 66 57 63 73 79 78 74 77 69 80
 76 70 71 75 72]


In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 38 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Id                1436 non-null   int64 
 1   Model             1436 non-null   object
 2   Price             1436 non-null   int64 
 3   Age_08_04         1436 non-null   int64 
 4   Mfg_Month         1436 non-null   int64 
 5   Mfg_Year          1436 non-null   int64 
 6   KM                1436 non-null   int64 
 7   Fuel_Type         1436 non-null   object
 8   HP                1436 non-null   int64 
 9   Met_Color         1436 non-null   int64 
 10  Color             1436 non-null   object
 11  Automatic         1436 non-null   int64 
 12  cc                1436 non-null   int64 
 13  Doors             1436 non-null   int64 
 14  Cylinders         1436 non-null   int64 
 15  Gears             1436 non-null   int64 
 16  Quarterly_Tax     1436 non-null   int64 
 17  Weight        

In [13]:
PR=df.iloc[:,2]
Age = df.iloc[:,3]
KM = df.iloc[:,6]
HP = df.iloc[:,8]
CC = df.iloc[:,12]
Drs = df.iloc[:,13]
Grs = df.iloc[:,15]
QT = df.iloc[:,16]
WT = df.iloc[:,17]
df1 = pd.DataFrame({"Price":PR,"Age":Age,"KM":KM,"HP":HP,"CC":CC,"Drs":Drs,"Grs":Grs,"QT":QT,"WT":WT})
df1

Price  Age     KM   HP    CC  Drs  Grs   QT    WT
0     13500   23  46986   90  2000    3    5  210  1165
1     13750   23  72937   90  2000    3    5  210  1165
2     13950   24  41711   90  2000    3    5  210  1165
3     14950   26  48000   90  2000    3    5  210  1165
4     13750   30  38500   90  2000    3    5  210  1170
...     ...  ...    ...  ...   ...  ...  ...  ...   ...
1431   7500   69  20544   86  1300    3    5   69  1025
1432  10845   72  19000   86  1300    3    5   69  1015
1433   8500   71  17016   86  1300    3    5   69  1015
1434   7250   70  16916   86  1300    3    5   69  1015
1435   6950   76      1  110  1600    5    5   19  1114

[1436 rows x 9 columns]

In [14]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   1436 non-null   int64
 1   Age     1436 non-null   int64
 2   KM      1436 non-null   int64
 3   HP      1436 non-null   int64
 4   CC      1436 non-null   int64
 5   Drs     1436 non-null   int64
 6   Grs     1436 non-null   int64
 7   QT      1436 non-null   int64
 8   WT      1436 non-null   int64
dtypes: int64(9)
memory usage: 101.1 KB


In [15]:
df1[df1.duplicated()]

Price  Age     KM   HP    CC  Drs  Grs   QT    WT
113  24950    8  13253  116  2000    5    5  234  1320

# Correlation_Matrix

In [16]:
df1.corr()

Price       Age        KM        HP        CC       Drs       Grs  \
Price  1.000000 -0.876590 -0.569960  0.314990  0.126389  0.185326  0.063104   
Age   -0.876590  1.000000  0.505672 -0.156622 -0.098084 -0.148359 -0.005364   
KM    -0.569960  0.505672  1.000000 -0.333538  0.102683 -0.036197  0.015023   
HP     0.314990 -0.156622 -0.333538  1.000000  0.035856  0.092424  0.209477   
CC     0.126389 -0.098084  0.102683  0.035856  1.000000  0.079903  0.014629   
Drs    0.185326 -0.148359 -0.036197  0.092424  0.079903  1.000000 -0.160141   
Grs    0.063104 -0.005364  0.015023  0.209477  0.014629 -0.160141  1.000000   
QT     0.219197 -0.198431  0.278165 -0.298432  0.306996  0.109363 -0.005452   
WT     0.581198 -0.470253 -0.028598  0.089614  0.335637  0.302618  0.020613   

             QT        WT  
Price  0.219197  0.581198  
Age   -0.198431 -0.470253  
KM     0.278165 -0.028598  
HP    -0.298432  0.089614  
CC     0.306996  0.335637  
Drs    0.109363  0.302618  
Grs   -0.005452  0.020613  
QT     1.000000  0.626134  
WT     0.626134  1.000000

In [ ]:
sns.set_style(style="darkgrid")
sns.pairplot(df1)

# Model_Building

In [ ]:
# Build Model
model = smf.ols("Price~Age+KM+HP+CC+Drs+Grs+QT+WT", data = df1).fit()

In [ ]:
# Coefficients
model.params

In [ ]:
# t values and p values:
model.tvalues, model.pvalues
# from below, p values for CC and Drs > 0.05, Hence we build SLR and MLR for variables CC and Drs.

In [ ]:
# Coefficient of determination: R Squared values
model.rsquared, model.rsquared_adj
# R squared value = 0.86% , Hence we can say line is good.

# Simple Linear Regression Models:
Build SLR and MLR models for insignificant variables 'CC' and 'Drs'
Also find their tvalues and pvalues

In [ ]:
ml_CC = smf.ols("Price~CC", data=df1).fit()
ml_CC.tvalues, ml_CC.pvalues

In [ ]:
ml_Drs = smf.ols("Price~Drs", data = df1).fit()
ml_Drs.tvalues, ml_Drs.pvalues

In [ ]:
ml_DC = smf.ols("Price~Drs+CC", data = df1).fit()
ml_DC.tvalues, ml_DC.pvalues

# Calculate VIF

In [ ]:
rsq_Age = smf.ols('Age~KM+HP+CC+Drs+Grs+QT+WT', data = df1).fit().rsquared
vif_Age = 1/(1-rsq_Age)
rsq_KM = smf.ols('KM~HP+CC+Drs+Grs+QT+WT+Age', data = df1).fit().rsquared
vif_KM = 1/ (1-rsq_KM)
rsq_HP = smf.ols('HP~CC+Drs+Grs+QT+WT+Age+KM', data = df1).fit().rsquared
vif_HP = 1/(1-rsq_HP)
rsq_CC = smf.ols('CC~Drs+Grs+QT+WT+Age+KM+HP', data = df1).fit().rsquared
vif_CC = 1/(1-rsq_CC)
rsq_Drs = smf.ols('Drs~Grs+QT+WT+Age+KM+HP+CC', data = df1).fit().rsquared
vif_Drs = 1/ (1-rsq_Drs)
rsq_Grs = smf.ols('Grs~QT+WT+Age+KM+HP+CC+Drs', data = df1).fit().rsquared
vif_Grs = 1/(1-rsq_Grs)
rsq_QT = smf.ols('QT~WT+Age+KM+HP+CC+Drs+Grs', data = df1).fit().rsquared
vif_QT = 1/(1-rsq_QT)
rsq_WT = smf.ols('WT~Age+KM+HP+CC+Drs+Grs+QT', data = df1).fit().rsquared
vif_WT = 1/ (1-rsq_WT)



d = {'Variables': ['Age','KM','HP','CC','Drs','Grs','QT','WT'], 'VIF': [vif_Age,vif_KM,vif_HP,vif_CC,vif_Drs,vif_Grs,vif_QT,vif_WT]}
d1 = pd.DataFrame(d)
print(d1)

In [ ]:
#VIF of all the variables < 20 , No collinearity.

# Residual Analysis
#Test for Normality of Residuals (Q-Q Plot) using residual model (model.resid)

In [ ]:
model = smf.ols("Price~Age+KM+HP+CC+Drs+Grs+QT+WT", data = df1).fit()

In [ ]:
import statsmodels.api as sm
import matplotlib.pyplot as plt
qqplot = sm.qqplot(model.resid, line = 'q')
plt.title("Normal Q-Q Plot of residual")

In [ ]:
import numpy as np
print(list(np.where(model.resid<-7000))) # outlier value exists below -7000 so that we use (model.resid<-70000)
print(list(np.where(model.resid>5000)))  # outlier value exists below 5000 so that we use (model.resid>50000)

In [ ]:
# Residual plot for Homoscedasticity or Heteroscedasticity

In [ ]:
model = smf.ols("Price~Age+KM+HP+CC+Drs+Grs+QT+WT", data = df1).fit()

In [ ]:
def get_standardized_values(vals):
    return(vals - vals.mean())/vals.std()
#get_standardized_values(df1)

In [ ]:
plt.figure(figsize=(10,7))
plt.scatter(get_standardized_values(model.fittedvalues),get_standardized_values(model.resid))
plt.title("Residual Plot", size=25)
plt.xlabel("Standardized fitted values")
plt.ylabel("Standardized residual values")
plt.show()

# Residual Vs Regressors

In [ ]:
fig = plt.figure(figsize = (15,10))
fig = sm.graphics.plot_regress_exog(model,"Age", fig = fig)
plt.show()

In [ ]:
fig = plt.figure(figsize = (15,10))
fig = sm.graphics.plot_regress_exog(model,"KM", fig = fig)
plt.show()

In [ ]:
fig = plt.figure(figsize = (15,10))
fig = sm.graphics.plot_regress_exog(model,"HP", fig = fig)
plt.show()

In [ ]:
fig = plt.figure(figsize = (15,10))
fig = sm.graphics.plot_regress_exog(model,"CC", fig = fig)
plt.show()

In [ ]:
fig = plt.figure(figsize = (15,10))
fig = sm.graphics.plot_regress_exog(model,"Drs", fig = fig)
plt.show()

In [ ]:
fig = plt.figure(figsize = (15,10))
fig = sm.graphics.plot_regress_exog(model,"Grs", fig = fig)
plt.show()

In [ ]:
fig = plt.figure(figsize = (15,10))
fig = sm.graphics.plot_regress_exog(model,"QT", fig = fig)
plt.show()

In [ ]:
fig = plt.figure(figsize = (15,10))
fig = sm.graphics.plot_regress_exog(model,"WT", fig = fig)
plt.show()

# Cook's Distance

In [ ]:
from statsmodels.graphics.regressionplots import influence_plot

model_influence_CC = model.get_influence()
(c_, _) = model_influence_CC.cooks_distance

In [ ]:
#Plot the influencers values using stem plot
fig = plt.subplots(figsize=(15, 7))
plt.stem(np.arange(len(df1)), np.round(c_, 3))
plt.xlabel('Row index')
plt.ylabel('Cooks Distance')
plt.show()

In [ ]:
#index and value of influencer where c is more than .5
(np.argmax(c_),np.max(c_))

In [ ]:
df1.shape

In [ ]:
k = df1.shape[1]
n = df1.shape[0]
leverage_cutoff = 3*((k + 1)/n)
leverage_cutoff

In [ ]:
from statsmodels.graphics.regressionplots import influence_plot
import matplotlib.pyplot as plt

influence_plot(model)
plt.show()
# From the above plot, Leverage Value using High Influence Points : Points beyond Leverage_cutoff value are influencers

In [ ]:
df1[df1.index.isin([80])]

In [ ]:
df2=df1.drop(df1.index[80], axis=0).reset_index()
df2.drop(['index'], axis=1, inplace=True)
df2

# Build Model

In [ ]:
#Exclude variable "CC" and generate R-Squared and AIC values
final_Drs = smf.ols('Price~Age+KM+HP+Drs+Grs+QT+WT',data = df2).fit()

In [ ]:
(final_Drs.rsquared, final_Drs.aic, final_Drs.bic)

In [ ]:
#Exclude variable "Drs" and generate R-Squared and AIC values
final_CC = smf.ols('Price~Age+KM+HP+CC+Grs+QT+WT',data = df2).fit()

In [ ]:
(final_CC.rsquared, final_CC.aic, final_CC.bic)

In [ ]:
##### Comparing above R-Squared and AIC values, model 'final_CC' has high R- square and low AIC value 
#hence include variable 'CC' so that multi collinearity problem would be resolved.

# Cook's Distance

In [ ]:
model_influence_CC = final_CC.get_influence()
(c_M, _) = model_influence_CC.cooks_distance

In [ ]:
#index and value of influencer where c is more than .5
(np.argmax(c_M),np.max(c_M))

In [ ]:
# Model Prediction for new dataset
# New data for prediction
new_data=pd.DataFrame({"Drs":3,"Age":24,"KM":58651,"HP":88,"CC":1500,"Grs":5,"QT":100,"WT":1101},index=[1])
new_data

In [ ]:
final_CC.predict(new_data)

In [ ]:
final_CC.predict(df2.iloc[0:9,])

In [ ]:
pred_y = final_CC.predict(df2)

In [ ]:
pred_y

# Table containing R^2 value for each prepared model

In [ ]:
d2={'Prep_Models':['Model','Final_Model'],'Rsquared':[model.rsquared,final_CC.rsquared]}
table=pd.DataFrame(d2)
table

In [ ]:
# Graph shows relation between Predicted and actual value
import matplotlib.pyplot as plt
df2.CC # Actual Value
pred_y   # Predicted Value
plt.plot(df2.CC,pred_y); plt.xlabel("Actual_CC_Value",size=15); plt.ylabel("Predicted_CC_Value",size = 15)
plt.title("Predicted Vs Actual CC Value Plot", size=20)
plt.show()